name: step_progress_indicator
description: Bar indicator made of a series of selected and unselected steps
version: 1.0.0-nullsafety.0
homepage: https://github.com/SandroMaglione/step-progress-indicator

environment:
  sdk: ">=2.12.0-259.16.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

