name: step_progress_indicator
description: Bar indicator made of a series of selected and unselected steps
version: 0.2.6+9
homepage: https://github.com/SandroMaglione/step-progress-indicator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

